//Removing state and importing JWT

const jwt = require("jsonwebtoken");
const secret = "Ayush$123@$" // this is the secret key

function setUser( user){
    return jwt.sign({   // sign and return the token
        _id: user._id,
        email: user.email,
    }, secret);
    //assigning user object as a payload
}

function getUser(token){
    // try and catch, because the user can send a wrong token as well
    try {
        return jwt.verify(token, secret); // verify if the token is generated by this secret key
    } catch (error) {
        return null;
    }
   
}

module.exports={
    setUser,
    getUser
};